name: Effekt Language
url: 'https://effekt-lang.github.io'
baseurl: '/effekt-website'
githuburl: https://github.com/effekt-lang/effekt
description: A research language with effect handlers and lightweight effect polymorphism
docs: true
highlighter: rouge
collections:
  tut:
    output: true
sass:
  load_paths:
  - _sass
  - _sass_custom
  style: compressed
  sourcemap: never
version: 0.1.0-SNAPSHOT
include:
- css/light-style.scss
- css/custom.scss
- css/fontawesome.min.css
- webfonts
- dist
org: docs
markdown: kramdown
