name: Effekt Language
url: 'https://effekt-lang.org'
baseurl:
githuburl: https://github.com/effekt-lang/effekt
description: A research language with effect handlers and lightweight effect polymorphism
docs: true
collections:
  tut:
    output: true
sass:
  load_paths:
  - _sass
  - _sass_custom
  style: compressed
  sourcemap: never
version: 0.1.0-SNAPSHOT
include:
- css/light-style.scss
- css/custom.scss
- css/fontawesome.min.css
- webfonts
- dist
exclude:
- effekt
org: docs
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
